Repository Automattic/liveblog, pull requests merged in 2018-10, with the labels that each got.

#536 remove commented-out debug code
  liveblog.php
Labels: Priority::High, confirmed bug

#534 Update the description to use the new "Vision" statement.
  README.md
  liveblog.php
  readme.txt
Labels: documentation, enhancement, has patch

#537 use proper ellipsis in get_entry_title()
  classes/class-wpcom-liveblog-entry.php
Labels: [Status] Ready to merge, enhancement

#513 Update readme.txt
  readme.txt
Labels: [Status] Ready to merge, documentation

#497 rerender oembed on update
  src/react/containers/EntryContainer.js
Labels: Priority::Low, [Status] Ready to merge, confirmed bug

#481 avoid null dereference in get_user_data_for_json()
  classes/class-wpcom-liveblog-entry.php
Labels: Priority::Medium, [Status] Ready to merge

#434 fix spelling of userdata
  classes/class-wpcom-liveblog-entry.php
Labels: [Status] Ready to merge

#419 Remove parentheses from require() and include() calls
  liveblog.php
Labels: [Status] Ready to merge

#486 PHPCS fixes for 1.9.1-dev
  .travis.yml
  README.md
  classes/class-wpcom-liveblog-amp-template.php
  classes/class-wpcom-liveblog-amp.php
  classes/class-wpcom-liveblog-cron.php
  classes/class-wpcom-liveblog-entry-embed-sdks.php
  classes/class-wpcom-liveblog-entry-embed.php
  classes/class-wpcom-liveblog-entry-extend-feature-authors.php
  classes/class-wpcom-liveblog-entry-extend-feature-commands.php
  classes/class-wpcom-liveblog-entry-extend-feature-emojis.php
  classes/class-wpcom-liveblog-entry-extend-feature-hashtags.php
  classes/class-wpcom-liveblog-entry-key-events.php
  classes/class-wpcom-liveblog-entry-query.php
  classes/class-wpcom-liveblog-entry.php
  classes/class-wpcom-liveblog-lazyloader.php
  classes/class-wpcom-liveblog-rest-api.php
  classes/class-wpcom-liveblog-socketio.php
  classes/class-wpcom-liveblog-wp-cli.php
  composer.json
  liveblog.php
  package-lock.json
  phpcs.xml.dist
  readme.txt
  t/bootstrap.php
  t/test-entry-query.php
  t/test-entry.php
  t/test-rest-api.php
  templates/amp/author.php
  templates/amp/entry.php
  templates/amp/feed.php
  templates/amp/pagination.php
  templates/liveblog-key-admin.php
  templates/liveblog-key-events.php
  templates/meta-box.php
  wpcom-helper.php
Labels: Needs testing, Priority::High

#510 Travis: Remove HHVM checks
  .travis.yml
Labels: [Status] Ready to merge, enhancement

#544 PHPCS fixes for v1.9.1
  classes/class-wpcom-liveblog-amp-template.php
  classes/class-wpcom-liveblog-amp.php
  liveblog.php
  templates/amp/entry.php
  templates/amp/feed.php
Labels: Priority::High, confirmed bug

#568 Add debounce to author list async box
  liveblog.php
  src/react/containers/EditorContainer.js
Labels: Needs testing

#572 Stop editors from publishing empty entries.
  src/react/containers/EditorContainer.js
Labels: Needs testing
